branches:
  only:
    - master
configuration: Release
before_build:
  - cmd: nuget restore
build:
  verbosity: normal
artifacts:
  - path: Foo\bin\$(configuration)\*.nupkg
nuget:
  account_feed: true
  project_feed: true
for:
  -
    branches:
      only:
        - master
      #This will reset the build number to zero.
      #It will always work as long as every merge to master is a different version
    install:
      - ps: Set-AppveyorBuildVariable -Name APPVEYOR_BUILD_NUMBER -Value 0
  -
    branches:
      only:
        - develop
    build_script:
      - dotnet build AppVeyorVersionTest.sln --version-suffix dev-{build}
