version: 5.9.18
branches:
  only:
    - master
configuration: Release
before_build:
  - cmd: nuget restore
build:
  verbosity: normal
artifacts:
  - path: Foo\bin\$(configuration)\*.*nupkg
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
#  version: '{version}'
  version_prefix: '{version}'
#  package_version: '{version}'
#  assembly_version: '{version}'
#  file_version: '{version}'
#  informational_version: '{version}'
nuget:
  account_feed: true
  project_feed: true
for:
  -
    branches:
      only:
        - master
      #This will reset the build number to zero.
      #It will always work as long as every merge to master is a different version
    install:
      - ps: |
          $apiUrl = 'https://ci.appveyor.com/api'
          $accountName = $env:APPVEYOR_ACCOUNT_NAME
          $projectSlug = $env:APPVEYOR_PROJECT_SLUG
          
          $headers = @{
            "Content-type" = "application/json"
            "Accept" = "application/json"
          }
          $build = @{
              nextBuildNumber = 0
          }
          $json = $build | ConvertTo-Json
          
          Invoke-RestMethod -Method Put $apiUrl/projects/$accountName/$projectSlug/settings/build-number -Body $json -Headers $headers
  -
    branches:
      only:
        - develop
    version: 5.9.18-dev{build}
